apiVersion: v1
kind: Pod
metadata:
  name: kubecost-grafana
  labels:
    app: kubecost-grafana
spec:
  containers:
  - name: kubecost
    image: kubecost/cost-model:latest
    ports:
    - containerPort: 9090
  - name: grafana
    image: grafana/grafana:latest
    ports:
    - containerPort: 3000
